### ISSUE TITLE
Swap doesnt happened but money deducted

### ISSUE THREAD

**Issue by gourav1601** [MuesliSwapTeam/muesliswap-cardano-pool-contracts#1]
Hash rate of txn but nothing happened

2047a68639e20d448cd0333628fd40313d4222485205f2659bb6a3c41e496b8f

**Comment by MuesliSwapTeam** [comment]
Hi, it might be that the price moved out of slippage. You can cancel any open swap request here: https://ada.muesliswap.com/orders - If you have further questions please feel free to text here or send us an email to contact@muesliswap.com. 

Please note: I will close the issue now as it's not related to the smart contract code in this repository :)
